version: '3.7'

services:
  api:
    build: './api/'
    container_name: backendapi_container
    volumes: 
      - ./api/:/home/Documents/BackendChallenger
    command: npm run dev
    ports:
      - '3000:3000'
    networks:
      - backend
  mongo:
    container_name: backendmongo_container
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'